pipeline{
	agent any
	
	stages{
	
		stage('Compile Stage'){
			steps{
				
					sh '''
          cd pipeline-master/demo2-master/demo1

	  cd demo1
          mvn clean install
    '''
		    }
	    }	
	}
}
